# Generated by Django 3.1.4 on 2020-12-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('followees', models.IntegerField(default=0)),
                ('followers', models.IntegerField(default=0)),
            ],
        ),
    ]
