# Generated by Django 3.1.4 on 2020-12-30 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_comments_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bioPost',
            field=models.CharField(default='No Bio', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='taggedUser',
            field=models.CharField(default='No Tagged User', max_length=200),
        ),
        migrations.AlterField(
            model_name='comments',
            name='sentiment',
            field=models.FloatField(default=0),
        ),
    ]
