# Generated by Django 3.1.4 on 2021-01-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_profile_ndatepostsaved'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='totalComments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='totalLikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='totalPost',
            field=models.IntegerField(default=0),
        ),
    ]
