# Generated by Django 3.1.4 on 2021-01-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20210103_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='bioPost',
            field=models.CharField(default='No Bio', max_length=500),
        ),
    ]
