# Generated by Django 3.1.4 on 2021-01-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20210103_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='bioPost',
            field=models.CharField(default='No Bio', max_length=1000),
        ),
    ]
