# Generated by Django 3.1.4 on 2021-01-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20210104_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='postContacts',
            field=models.IntegerField(default=0),
        ),
    ]
