# Generated by Django 3.1.4 on 2021-01-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_profile_postcontacts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='totalPost',
        ),
        migrations.AddField(
            model_name='profile',
            name='allPost',
            field=models.IntegerField(default=0),
        ),
    ]
