# Generated by Django 3.1.4 on 2021-01-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20210105_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='id_social',
            field=models.IntegerField(default=0),
        ),
    ]
