# Generated by Django 3.1.4 on 2021-01-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_comments_id_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='owner',
            field=models.CharField(default='No owner', max_length=200),
        ),
    ]
