# Generated by Django 3.1.4 on 2021-01-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20210105_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='language',
            field=models.CharField(default='No Language', max_length=200),
        ),
    ]
