# Generated by Django 3.1.4 on 2021-01-05 16:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20210105_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='datePost',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
