# Generated by Django 3.1.4 on 2021-01-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_all_social_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isPrivate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='totalComments',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='totalLikes',
            field=models.BigIntegerField(default=0),
        ),
    ]
