# Generated by Django 3.1.4 on 2021-01-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_auto_20210123_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='avgSentiment',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_text',
            field=models.CharField(max_length=500),
        ),
    ]
