# Generated by Django 3.1.4 on 2021-02-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_auto_20210127_1841'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-likesCount']},
        ),
        migrations.AddField(
            model_name='comments',
            name='negative',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='neutral',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='positive',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='sentiment',
            field=models.CharField(default='Not Analyzed', max_length=10),
        ),
    ]
