# Generated by Django 3.1.4 on 2021-02-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_auto_20210212_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='sentiment',
            field=models.CharField(default='Not Analyzed', max_length=20),
        ),
    ]
