# Generated by Django 3.1.4 on 2021-02-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_auto_20210212_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='avgSentiment',
        ),
        migrations.AddField(
            model_name='post',
            name='avgNegativeSentiment',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='post',
            name='avgNeutralSentiment',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='post',
            name='avgPositiveSentiment',
            field=models.FloatField(default=0.0),
        ),
    ]
