# Generated by Django 3.1.4 on 2021-02-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0023_auto_20210212_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='nCommentsCount',
            field=models.IntegerField(default=0),
        ),
    ]
