# Generated by Django 3.1.4 on 2021-02-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0024_post_ncommentscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avgNegativeSentiment',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='profile',
            name='avgNeutralSentiment',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='profile',
            name='avgPositiveSentiment',
            field=models.FloatField(default=0.0),
        ),
    ]
