# Generated by Django 3.1.4 on 2021-02-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0025_auto_20210216_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='avgNegativeSentiment',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='avgNeutralSentiment',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='avgPositiveSentiment',
            field=models.FloatField(null=True),
        ),
    ]
